USE [master]
GO

/****** Object:  Database [todolist]    Script Date: 08/05/2026 08:50:15 p. m. ******/
CREATE DATABASE [todolist]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'todolist', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\todolist.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'todolist_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\todolist_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [todolist].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [todolist] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [todolist] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [todolist] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [todolist] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [todolist] SET ARITHABORT OFF 
GO

ALTER DATABASE [todolist] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [todolist] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [todolist] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [todolist] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [todolist] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [todolist] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [todolist] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [todolist] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [todolist] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [todolist] SET  DISABLE_BROKER 
GO

ALTER DATABASE [todolist] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [todolist] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [todolist] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [todolist] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [todolist] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [todolist] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [todolist] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [todolist] SET RECOVERY FULL 
GO

ALTER DATABASE [todolist] SET  MULTI_USER 
GO

ALTER DATABASE [todolist] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [todolist] SET DB_CHAINING OFF 
GO

ALTER DATABASE [todolist] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [todolist] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [todolist] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [todolist] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [todolist] SET QUERY_STORE = OFF
GO

ALTER DATABASE [todolist] SET  READ_WRITE 
GO


